#!/bin/bash

# Task 6: Stop me if you can
# Find the PID of the "4-to_infinity_and_beyond" process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# If the process is found, terminate it
if [ -n "$pid" ]; then
    kill "$pid"
fi
