#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data

awk '{count[$1" "$9]++} END {for (ip_status in count) {print count[ip_status], ip_status}}' apache-access.log | sort -nr
