#!/usr/bin/env bash
# This script displays the content of the current directory with only the part of the name after the first dash

for file in *
do
    name=$(echo "$file" | cut -d '-' -f 2-)
    echo "$name"
done
